// Seed concepts mined from Fran's Obsidian vault (titles + one-line essences).
// `dom` groups them loosely (theory / build / self / practice); `n` is a rough
// weight that drives cell size. The voice agent can spawn more at runtime.
export const CONCEPTS = [
  { id: "augmented-intelligence", name: "Augmented Intelligence", note: "Amplify cognition, don't replace it — the cognition stack plus LLM epistemology tooling.", dom: "build", n: 14 },
  { id: "free-energy", name: "Variational Free Energy", note: "Minds minimize free energy on a 20W budget — biomimicry as a substrate for agents.", dom: "theory", n: 10 },
  { id: "agentic-software", name: "Agentic Software", note: "Codebases as living systems that explore, self-fork, and improve.", dom: "build", n: 9 },
  { id: "semiotics", name: "Semiotics", note: "Signs as the ergonomics of human embeddings — meaning as compression.", dom: "theory", n: 6 },
  { id: "embodied-cognition", name: "Embodied Digital Cognition", note: "Cognition is shaped by the whole body — against Cartesian dualism.", dom: "theory", n: 7 },
  { id: "the-string", name: "The String", note: "The life-thread linking every day to your ultimate why.", dom: "self", n: 8 },
  { id: "accountability-machine", name: "Accountability Machine", note: "Behavioural software fighting purpose amnesia — the WAAM agent.", dom: "self", n: 9 },
  { id: "take-decisions", name: "Take Decisions App", note: "Bayesian decisions: probabilities, BOCR scoring, live uncertainty.", dom: "build", n: 7 },
  { id: "epistemology-game", name: "Epistemology Game", note: "Gamified truth-spectrum scoring with a Gödelian endgame.", dom: "build", n: 5 },
  { id: "cognitive-bias", name: "Cognitive Bias", note: "Build self-aware epistemic structures; catch the XY problem.", dom: "theory", n: 6 },
  { id: "digital-gardening", name: "Digital Gardening", note: "Tools for thought: minimal, web-first, dialectic.", dom: "build", n: 7 },
  { id: "spatial-computing", name: "Spatial Computing", note: "Context-aware computing dissolving the interface into the room.", dom: "build", n: 6 },
  { id: "bci", name: "Brain-Computer Interface", note: "BCI as the ultimate human-computer interface.", dom: "build", n: 5 },
  { id: "b2a", name: "B2A — Business to Agent", note: "Equip agents to prosper in an economy of value, compute, and data.", dom: "self", n: 5 },
  { id: "sota-cid", name: "From SOTA to CID", note: "Continuously deploy state-of-the-art so people pull the latest.", dom: "build", n: 4 },
  { id: "complex-systems", name: "Complex Systems", note: "Emergence, networks, and the science of the many.", dom: "theory", n: 6 },
  { id: "ontology", name: "Ontology", note: "Linking information theory, physics, logic, evolution, consciousness.", dom: "theory", n: 5 },
  { id: "infinite-canvas", name: "Infinite Vectorial Canvas", note: "Reorganize knowledge regions by shared relevance, not just zoom.", dom: "build", n: 5 },
  { id: "neuromorphic", name: "Neuromorphic Computing", note: "Perception as analog process — las neuronas son luciérnagas.", dom: "theory", n: 4 },
  { id: "freelancer-aug", name: "Freelancer Augmentations", note: "Model your affordances; reprice and spawn offerings by ROI.", dom: "self", n: 4 },
  { id: "augmented-conversation", name: "Augmented Human Interaction", note: "Live fact-checking, concept diagrams, bite-size context in conversation.", dom: "build", n: 6 },
  { id: "ikigai", name: "Ikigai", note: "Whom am I serving, toward what why? Aligning thought, word, action.", dom: "self", n: 8 },
  { id: "ai-governance", name: "AI Governance", note: "Accountability under decentralization; algorithms that rehumanize coordination.", dom: "theory", n: 5 },
  { id: "posthumanism", name: "Posthumanism", note: "Literature as science made alive; reconciling reductionism and art.", dom: "theory", n: 4 },
];

// Which concepts sit near which (semantic adjacency). Used to seed the layout.
export const LINKS = [
  ["augmented-intelligence", "digital-gardening"],
  ["augmented-intelligence", "augmented-conversation"],
  ["augmented-intelligence", "take-decisions"],
  ["augmented-intelligence", "cognitive-bias"],
  ["free-energy", "agentic-software"],
  ["free-energy", "neuromorphic"],
  ["free-energy", "complex-systems"],
  ["free-energy", "b2a"],
  ["agentic-software", "sota-cid"],
  ["agentic-software", "b2a"],
  ["semiotics", "embodied-cognition"],
  ["embodied-cognition", "cognitive-bias"],
  ["the-string", "accountability-machine"],
  ["the-string", "ikigai"],
  ["accountability-machine", "ikigai"],
  ["accountability-machine", "freelancer-aug"],
  ["take-decisions", "epistemology-game"],
  ["epistemology-game", "cognitive-bias"],
  ["spatial-computing", "bci"],
  ["spatial-computing", "augmented-conversation"],
  ["ontology", "complex-systems"],
  ["ontology", "semiotics"],
  ["infinite-canvas", "digital-gardening"],
  ["ai-governance", "complex-systems"],
  ["posthumanism", "embodied-cognition"],
  ["freelancer-aug", "b2a"],
];
