// A hand-curated constellation from Fran's Obsidian vault.
// Each record is intentionally small: enough to spark a thought, not flatten the note.
export const CONCEPTS = [
  {
    id: "augmented-intelligence",
    name: "Augmented Intelligence",
    kind: "thesis",
    fragment: "Amplify cognition; do not replace it.",
    note: "A cognition stack in which language models extend agency, retrieval, planning, conversation, and epistemic judgment while leaving a human meaningfully in the loop.",
    question: "What should a mind keep for itself, even when delegation is effortless?",
    source: "Augmented Intelligence.md",
    tags: ["ai", "cognition", "agency", "human", "epistemology"],
    n: 14,
  },
  {
    id: "digital-gardening",
    name: "Think Through the Software",
    kind: "principle",
    fragment: "Your computer is the neo-neo-cortex.",
    note: "Tools for thought should resemble intuitive patterns of thinking: minimal, web-first, dialectical, and permissive enough that a question can become an answer that becomes another question.",
    question: "Does this tool help you think—or merely help you store what you already thought?",
    source: "Digital Gardening.md",
    tags: ["obsidian", "garden", "tools for thought", "web", "dialectic"],
    n: 10,
  },
  {
    id: "cognitive-clutch",
    name: "Cognitive Clutch",
    kind: "mechanism",
    fragment: "A smooth, deliberate engagement from idea to action—and idea to idea.",
    note: "A tiny metaphor for behavioural software: good cognitive interfaces do not yank attention. They let intention engage with resistance, timing, and feel.",
    question: "Where does your thinking currently grind its gears?",
    source: "cognitive clutch.md",
    tags: ["attention", "action", "semiotics", "behaviour", "interface"],
    n: 7,
  },
  {
    id: "the-string",
    name: "The String",
    kind: "life system",
    fragment: "The thread that gives sense to your actions.",
    note: "The overall thought process linking one day to the next: intention, recurring thoughts, calendars, feedback, and the ultimate self-monologue that keeps a life from becoming unrelated moments.",
    question: "What is the smallest action today that still belongs to your ultimate why?",
    source: "The String.md",
    tags: ["purpose", "life", "calendar", "meaning", "why"],
    n: 12,
  },
  {
    id: "context-not-memory",
    name: "Forget Memory. It’s All Context.",
    kind: "provocation",
    fragment: "Future-you does not need every fact. Future-you needs the right graph for the moment.",
    note: "The vault becomes useful when it can load a situated constellation around the present need—not when it behaves like a perfect warehouse of isolated recollections.",
    question: "What context would make this thought actionable five years from now?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["memory", "context", "retrieval", "graph", "future self"],
    n: 10,
  },
  {
    id: "metabolic-thinking",
    name: "Metabolic Thinking",
    kind: "mental model",
    fragment: "Explore, then exploit. Grow, then metabolise.",
    note: "Thinking alternates between an anabolic mode that produces options and a catabolic mode that chooses and acts. A working guess: 20% exploration, 80% execution—mindful, Bayesian, and never rigid.",
    question: "Do you need another option, or do you need to digest the ones you have?",
    source: "Metabolic Thinking.md",
    tags: ["explore exploit", "decision", "mental model", "80/20", "bayesian"],
    n: 9,
  },
  {
    id: "architect-gardener",
    name: "Architect / Gardener",
    kind: "tension",
    fragment: "Structure and curiosity are not personalities. They are hats.",
    note: "Architects work top-down from a picture of the whole. Gardeners work bottom-up through play and unexpected connections. The useful skill is sensing when to switch modes.",
    question: "Are you stuck in weeds, or building structure you have not earned?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["creative process", "structure", "curiosity", "garden", "architecture"],
    n: 8,
  },
  {
    id: "fractal-embodiment",
    name: "Fractal Embodiment",
    kind: "thesis",
    fragment: "Intelligence lives in overlapping Matryoshkas.",
    note: "Cells, organs, people, and social groups behave as nested agents with distinct affordances. Knowledge is always local—instantiated in matter—yet resonates across scales.",
    question: "At which scale does this problem become intelligent?",
    source: "Fractal embodiment.md",
    tags: ["intelligence", "biology", "scale", "agents", "embodiment"],
    n: 11,
  },
  {
    id: "neurons-fireflies",
    name: "Neurons Are Fireflies",
    kind: "memory",
    fragment: "Perception makes sense because the process is analog.",
    note: "A frightening altered state became an intuition: stable experience emerges from living, continuous processes—not just discrete symbols. Later, the idea found a technical neighbour in neuromorphic computing.",
    question: "What can continuous experience express that a sequence of tokens cannot?",
    source: "\“Las neuronas son luciernagas\”.md",
    tags: ["neuromorphic", "analog", "perception", "memory", "brain"],
    n: 9,
  },
  {
    id: "free-energy",
    name: "Twenty-Watt Intelligence",
    kind: "question",
    fragment: "Minds minimise surprise on a twenty-watt budget.",
    note: "Variational free energy suggests a biomimetic frontier: adaptive agents that continuously predict and update without requiring the industrial appetite of brute-force computation.",
    question: "What would software feel like if energy—not scale—were the primary constraint?",
    source: "variational free energy.md",
    tags: ["free energy", "biomimicry", "efficiency", "brain", "prediction"],
    n: 10,
  },
  {
    id: "embodied-cognition",
    name: "The Body Is in the Thought",
    kind: "thesis",
    fragment: "Cognition is shaped by the entire organism.",
    note: "Reasoning, judgment, and concepts are not sealed in an abstract processor. They are shaped by motor systems, perception, situated action, and a body's learned assumptions about its world.",
    question: "Which part of this idea changes when the body changes?",
    source: "Embodied Digital Cognition.md",
    tags: ["body", "cognition", "enactivism", "situated", "perception"],
    n: 9,
  },
  {
    id: "semiotics",
    name: "Signs as Human Embeddings",
    kind: "lens",
    fragment: "Meaning is compression with handles.",
    note: "Symbols, interfaces, diagrams, and language let humans navigate compressed regions of meaning. Semiotics is not ornament; it is the ergonomics of retrieval and shared thought.",
    question: "What is the smallest sign that could carry this whole idea?",
    source: "Semiotics.md",
    tags: ["signs", "meaning", "information", "interface", "language"],
    n: 8,
  },
  {
    id: "future-ui",
    name: "Interface After Buttons",
    kind: "interface",
    fragment: "Abstract the user from the buttons all along.",
    note: "Language-based, spatial, context-aware computing can bridge unstructured intention and structured action. Controls become temporary expressions of what the moment affords.",
    question: "If the interface knew the context, which controls would cease to exist?",
    source: "The future of UI.md",
    tags: ["generative ui", "context", "spatial", "language", "interaction"],
    n: 12,
  },
  {
    id: "disappearing-buttons",
    name: "Buttons That Fade Away",
    kind: "interface",
    fragment: "Make a button that never existed before.",
    note: "When a structured action becomes relevant inside a language interaction, surface the exact control—send, choose, schedule, tune—then let it slowly disappear when its moment passes.",
    question: "What control does this particular sentence need?",
    source: "The future of UI.md",
    tags: ["buttons", "generative ui", "ephemeral", "action", "controls"],
    n: 8,
  },
  {
    id: "semantic-proximity",
    name: "Semantic Proximity",
    kind: "interface",
    fragment: "Let relevant knowledge drift toward the conversation.",
    note: "As people speak, bite-sized fragments from a second brain appear like magnetic, translucent bubbles—growing as their relevance increases, receding without demanding attention.",
    question: "How close can context come before it interrupts?",
    source: "augmented human interaction.md",
    tags: ["conversation", "context", "relevance", "bubbles", "second brain"],
    n: 9,
  },
  {
    id: "tactile-error",
    name: "Tactile Prediction Errors",
    kind: "interface",
    fragment: "Feel the size of your surprise.",
    note: "A haptic pulse could make prediction error tangible: duration, force, and texture varying with how far reality diverges from expectation.",
    question: "Which mistake should be felt before it is explained?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["haptics", "prediction", "error", "bayesian", "tactile"],
    n: 7,
  },
  {
    id: "attention-layer",
    name: "The Attention Layer",
    kind: "interface",
    fragment: "Eyes plus voice make context visible.",
    note: "Eye tracking contributes a heat map of attention while speech contributes intent. Together they create a richer semantic context than either pointer or prompt can offer alone.",
    question: "What does your gaze reveal that your words omit?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["eye tracking", "voice", "attention", "context", "spatial computing"],
    n: 7,
  },
  {
    id: "augmented-conversation",
    name: "Conversation, Augmented",
    kind: "prototype",
    fragment: "A second brain at the edge of the dialogue.",
    note: "Live diagrams, fact checks, fallacy checks, public-opinion context, and editable concept maps accompany a conversation without taking it over.",
    question: "Can a conversation gain instrumentation without losing intimacy?",
    source: "augmented human interaction.md",
    tags: ["conversation", "fact check", "diagram", "collaboration", "podcast"],
    n: 9,
  },
  {
    id: "thought-provoking-scores",
    name: "Thought-Provoking Scores",
    kind: "prototype",
    fragment: "Can an idea report how much thinking it might cause?",
    note: "A playful scoring loop ranks statements from banal to generative, then asks a model to mutate an input into something more capable of producing reflection.",
    question: "Is provocation a property of a sentence, or of the mind meeting it?",
    source: "Thought-provoking Scores..md",
    tags: ["score", "reflection", "llm", "idea", "ranking"],
    n: 6,
  },
  {
    id: "epistemology-game",
    name: "The Epistemology Game",
    kind: "prototype",
    fragment: "Learn the limits of certainty by trying to win at it.",
    note: "A game about induction, abduction, syllogisms, social knowledge, and truth spectra—ending, inevitably, with a Gödelian joke about the system's inability to finish itself.",
    question: "What would count as winning a game whose lesson is incompleteness?",
    source: "Epistemology Game.md",
    tags: ["truth", "logic", "godel", "game", "social epistemology"],
    n: 8,
  },
  {
    id: "take-decisions",
    name: "Decisions in Probabilities",
    kind: "prototype",
    fragment: "Replace false certainty with live uncertainty.",
    note: "A decision tool combining Bayesian probabilities with benefits, opportunities, costs, and risks—keeping the assumptions visible enough to change when evidence arrives.",
    question: "Which assumption would reverse the decision if it moved by ten percent?",
    source: "Take decisions app.md",
    tags: ["decision", "bayesian", "probability", "risk", "uncertainty"],
    n: 8,
  },
  {
    id: "uncertainty-overlay",
    name: "Bayes Over Fuzz",
    kind: "mechanism",
    fragment: "An overlay of mathematical probability on human vagueness.",
    note: "Fuzzy logic handles nuance and partial membership; Bayesian reasoning updates belief. Together they suggest interfaces that admit imprecision without abandoning rigor.",
    question: "Can uncertainty be made legible without pretending it is simple?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["bayesian", "fuzzy logic", "probability", "uncertainty", "interface"],
    n: 8,
  },
  {
    id: "agentic-software",
    name: "Agentic Software",
    kind: "system",
    fragment: "Codebases as living systems that explore, fork, and improve.",
    note: "Software becomes less like a finished machine and more like a population of situated agents: proposing changes, testing hypotheses, asking for attention, and continuously deploying better strategies.",
    question: "When software can change itself, what deserves to remain deliberately inert?",
    source: "Agentic Software.md",
    tags: ["agents", "software", "self evolving", "code", "deployment"],
    n: 11,
  },
  {
    id: "bonsai-containers",
    name: "Kubernetes for Bonsai",
    kind: "metaphor",
    fragment: "Orchestrate small cultivated contexts, not one giant memory.",
    note: "The knowledge system becomes a collection of tended, bounded thought environments. The String is the orchestration layer that loads and connects the right living container.",
    question: "Which context deserves a pot, and which should be allowed to grow wild?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["context", "orchestration", "bonsai", "memory", "containers"],
    n: 7,
  },
  {
    id: "sorrow-solver",
    name: "Sorrow Solver",
    kind: "tiny prototype",
    fragment: "Add a pedantic class first.",
    note: "A deliberately literal software sketch: accept a list of sorrows and return compassionate next steps. Half joke, half question about what kinds of pain become tractable when named.",
    question: "Which sorrows need a solution, and which need witness?",
    source: "sorrow solver.md",
    tags: ["prototype", "emotion", "care", "software", "compassion"],
    n: 6,
  },
  {
    id: "ear-plane",
    name: "Ear Plane",
    kind: "tiny prototype",
    fragment: "A small app for a very specific pressure.",
    note: "An idea for easing the ear pain of flying when equalisation fails—a reminder that useful software can begin with one awkward, embodied moment.",
    question: "What recurring discomfort is too small for a market and large enough for a person?",
    source: "Ear Plane.md",
    tags: ["flight", "pain", "prototype", "body", "small app"],
    n: 5,
  },
  {
    id: "social-mindfulness",
    name: "Infrastructure for Emptiness",
    kind: "observation",
    fragment: "A park. A bench. A library. Free RAM for a society.",
    note: "Some civic ideas do not prescribe a life; they grant space for lives to unfold. DOKK1, parks, and shared infrastructure become a matrix of zeroes—a canvas that creates useful vacuum.",
    question: "Which institutions create room instead of filling it?",
    source: "Towards social Mindfulness.md",
    tags: ["society", "mindfulness", "infrastructure", "space", "DOKK1"],
    n: 8,
  },
  {
    id: "mind-palace",
    name: "The Unspoken Tragedy",
    kind: "conviction",
    fragment: "Most people do not bloom to their full potential.",
    note: "The mind is a palace that requires carefully crafted inputs. Augmented decision-making matters because better prediction is ultimately in service of people becoming more capable of blooming.",
    question: "What input would make one dormant room of the mind habitable?",
    source: "What The World Needs.md",
    tags: ["potential", "mind", "input", "prediction", "human flourishing"],
    n: 9,
  },
  {
    id: "literature-alive",
    name: "Science Made Alive",
    kind: "bridge",
    fragment: "Literature is not science's antithesis; it is science made alive.",
    note: "Art and literature model possible states of consciousness and desirable forms of being. They reconcile reduction with experience by letting an explanation inhabit a life.",
    question: "What does this explanation become when somebody has to live inside it?",
    source: "Posthumanism Talk IMC.md",
    tags: ["literature", "science", "art", "consciousness", "posthumanism"],
    n: 8,
  },
  {
    id: "accountability-machine",
    name: "The Accountability Machine",
    kind: "life system",
    fragment: "Behavioural software against purpose amnesia.",
    note: "A personal agent that notices chronic patterns, keeps intentions close, and creates a bridge between the person who made a commitment and the person who wakes up tomorrow.",
    question: "How can a system remember your promise without becoming your parent?",
    source: "accountability machine.md",
    tags: ["accountability", "behaviour", "purpose", "agent", "habits"],
    n: 10,
  },
  {
    id: "infinite-canvas",
    name: "Infinite Vectorial Canvas",
    kind: "interface",
    fragment: "Reorganise regions by relevance, not only by zoom.",
    note: "A spatial knowledge surface where concepts can reshape their neighbourhoods as context changes. Distance becomes semantic, and scale becomes a way of choosing what kind of relation matters.",
    question: "If meaning controlled distance, what would move closer right now?",
    source: "Infinite Vectorial Canvas.md",
    tags: ["canvas", "spatial", "knowledge", "relevance", "zoom"],
    n: 9,
  },
  {
    id: "metaculus-self",
    name: "The Metaculus of the Self",
    kind: "question",
    fragment: "Forecast your own attention, error, and becoming.",
    note: "A personal forecasting layer asks not only what the world will do, but which future self will need attention—and which current hypotheses are quietly drifting away from the probable.",
    question: "What about your own behaviour should you be assigning probabilities to?",
    source: "The Ergonomics of Augmented Reasoning.md",
    tags: ["forecast", "self", "probability", "attention", "metacognition"],
    n: 7,
  },
];

// The third value is the thought carried by the connection. It appears when
// visitors follow a thread, making the links part of the reading experience.
export const LINKS = [
  ["augmented-intelligence", "digital-gardening", "the tool should extend the shape of thought"],
  ["augmented-intelligence", "agentic-software", "augmentation requires delegated agency"],
  ["augmented-intelligence", "mind-palace", "capability should serve human flourishing"],
  ["digital-gardening", "context-not-memory", "retrieval matters more than accumulation"],
  ["digital-gardening", "architect-gardener", "a garden needs both paths and wildness"],
  ["digital-gardening", "infinite-canvas", "spatial tools can become thought environments"],
  ["cognitive-clutch", "tactile-error", "good feedback has resistance and feel"],
  ["cognitive-clutch", "the-string", "intention needs a smooth route into action"],
  ["the-string", "context-not-memory", "context reconnects the day to the life"],
  ["the-string", "accountability-machine", "a promise must survive the person who made it"],
  ["the-string", "bonsai-containers", "orchestration loads the right cultivated context"],
  ["metabolic-thinking", "architect-gardener", "both ask when to explore and when to structure"],
  ["metabolic-thinking", "take-decisions", "options become action through explicit judgment"],
  ["architect-gardener", "agentic-software", "living systems balance cultivation and constraint"],
  ["fractal-embodiment", "embodied-cognition", "intelligence is situated at every scale"],
  ["fractal-embodiment", "free-energy", "nested agents maintain themselves by predicting"],
  ["fractal-embodiment", "social-mindfulness", "bodies become groups; groups shape bodies"],
  ["neurons-fireflies", "free-energy", "continuous perception stabilises a world"],
  ["neurons-fireflies", "embodied-cognition", "an altered body reveals the architecture of experience"],
  ["free-energy", "agentic-software", "biological efficiency becomes a software ideal"],
  ["embodied-cognition", "ear-plane", "small bodily frictions can originate useful systems"],
  ["embodied-cognition", "tactile-error", "reasoning can enter the body through feedback"],
  ["semiotics", "cognitive-clutch", "a sign is where thought engages with action"],
  ["semiotics", "future-ui", "interfaces compress possible action into legible signs"],
  ["semiotics", "literature-alive", "symbols make explanations inhabitable"],
  ["future-ui", "disappearing-buttons", "controls become temporary products of context"],
  ["future-ui", "attention-layer", "context comes from more than language"],
  ["future-ui", "infinite-canvas", "space becomes an adaptive interface"],
  ["disappearing-buttons", "semantic-proximity", "relevance should surface gently, then recede"],
  ["semantic-proximity", "augmented-conversation", "nearby knowledge can enrich live dialogue"],
  ["semantic-proximity", "context-not-memory", "the right fragment arrives for this moment"],
  ["attention-layer", "augmented-conversation", "conversation gains a second channel of context"],
  ["thought-provoking-scores", "epistemology-game", "reflection becomes playable"],
  ["thought-provoking-scores", "metaculus-self", "the mind turns evaluation back on itself"],
  ["epistemology-game", "uncertainty-overlay", "truth becomes a spectrum with rules"],
  ["epistemology-game", "literature-alive", "the game needs irony at the edge of formal systems"],
  ["take-decisions", "uncertainty-overlay", "decisions stay live when confidence stays visible"],
  ["take-decisions", "metaculus-self", "prediction becomes personal practice"],
  ["agentic-software", "bonsai-containers", "agents need bounded contexts and orchestration"],
  ["agentic-software", "sorrow-solver", "a living system can still start as a tiny function"],
  ["sorrow-solver", "mind-palace", "care asks what helps a person bloom"],
  ["ear-plane", "disappearing-buttons", "the most useful control may exist for one moment"],
  ["social-mindfulness", "mind-palace", "good infrastructure makes room for potential"],
  ["social-mindfulness", "literature-alive", "shared space needs stories of possible lives"],
  ["accountability-machine", "metaculus-self", "self-knowledge improves through forecasts and feedback"],
  ["infinite-canvas", "context-not-memory", "the graph reorganises around the present"],
  ["infinite-canvas", "fractal-embodiment", "scale changes which agents and relations appear"],
];
